#!/bin/bash

# Script untuk instalasi WordPress dengan Nginx dan PHP 8.3 pada VPS Ubuntu

# Periksa apakah script dijalankan dengan hak akses root
if [[ $EUID -ne 0 ]]; then
   echo "Script ini harus dijalankan sebagai root atau dengan sudo"
   exit 1
fi

# Tambahkan repositori PHP 8.3
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update

# Install Nginx, MySQL, dan PHP 8.3 serta ekstensi yang diperlukan
sudo apt-get install -y nginx php8.3-fpm php8.3-mysql php8.3-curl php8.3-gd php8.3-mbstring php8.3-xml php8.3-xmlrpc php8.3-soap php8.3-intl php8.3-zip unzip

# Konfigurasi MySQL
apt-get install -y mariadb-server;

# Langkah 2: Konfigurasi database MySQL
mysql -e "CREATE DATABASE ${DB_NAME} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
mysql -e "GRANT ALL ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"


# Membuat file konfigurasi Nginx
cat <<EOL > $NGINX_CONF
server {
        listen 80;
        root /var/www/html/hendra56.my.id;
        index index.php index.html index.htm index.nginx-debian.html;
        server_name hendra56.my.id;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        }

        location ~ /\.ht {
                deny all;
        }
}
EOL

# Aktifkan konfigurasi Nginx
sudo ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl reload nginx

# Unduh WordPress
wget https://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz -C /var/www/html/
rm latest.tar.gz

# Konfigurasi WordPress
sudo cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
sudo sed -i 's/database_name_here/wordpress/' /var/www/html/wordpress/wp-config.php
sudo sed -i 's/username_here/wordpressuser/' /var/www/html/wordpress/wp-config.php
sudo sed -i 's/password_here/password/' /var/www/html/wordpress/wp-config.php

# Setel hak akses
sudo chown -R www-data:www-data /var/www/html/wordpress
sudo chmod -R 755 /var/www/html/wordpress

# Selesai
echo "Instalasi WordPress dengan Nginx dan PHP 8.3 selesai. Anda bisa mengakses situs Anda pada http://your_domain.com"
